NAME: prohmr_flow_with_transl_input

DATASETS:
  PATH: /data/hdd1/qf/hithand_data/ffhnet-data
  GAZEBO_OBJ_PATH: /home/yb/Projects/gazebo-objects
  GRASP_DATA_NANE: grasp_data_all.h5

GENERAL:
  TOTAL_STEPS: 200000 #100000 for train with nll and second 100000 for fintune
  LOG_STEPS: 100
  VAL_STEPS: 100
  CHECKPOINT_STEPS: 1000
  NUM_WORKERS: 8

TRAIN:
  LR: 1e-4
  # WEIGHT_DECAY: 1e-4
  BATCH_SIZE: 64
  LOSS_REDUCTION: mean
  NUM_TRAIN_SAMPLES: 1
  NUM_TEST_SAMPLES: 100
  POSE_2D_NOISE_RATIO: 0.01
  SMPL_PARAM_NOISE_RATIO: 0.005
  # from ffhnet
  BETA1: 0.9
  WEIGHT_DECAY: 0.0005

LOSS_WEIGHTS:
  GLOBAL_ORIENT_EXP: 0.000
  GLOBAL_ORIENT_MODE: 0.001
  BODY_POSE_EXP: 0.0
  BODY_POSE_MODE: 0.001
  ORTHOGONAL: 0.1
  BETAS_EXP: 0.0
  BETAS_MODE: 0.0005
  NLL: 0.001
  ADVERSARIAL: 0.0005
  ROT: 0.1 # TODO: to be tuned
  TRANSL: 0.1 # In FFHNet, transl coef is 100x of rot coef

MODEL:
  IMAGE_SIZE: 224
  IMAGE_MEAN: [0.485, 0.456, 0.406]
  IMAGE_STD: [0.229, 0.224, 0.225]
  BACKBONE:
    #FFHGenerator
    LATENT_DIM: 5

  FLOW:
    DIM: 63 # input dims
    NUM_LAYERS: 4 # numbers of layers about [Actnorm, LULinear, Coupling]
    CONTEXT_FEATURES: 512 # features dim from backbone
    LAYER_HIDDEN_FEATURES: 512 #1024 # hidden layer dims in resnet inside Glow
    LAYER_DEPTH: 2 # number of resblock in setnet
  FC_HEAD:
    NUM_FEATURES: 1024

EXTRA:
  FOCAL_LENGTH: 5000
  NUM_LOG_IMAGES: 4
  NUM_LOG_SAMPLES_PER_IMAGE: 8
  PELVIS_IND: 39
