NAME: test_lvm_cond_gaussian_prior_flow_0.01_10k
BASE_PACKAGE: normflows # nflows

DATASETS:
  PATH: /data/net/userstore/qf/hithand_data/data/ffhnet-data # /data/hdd1/qf/hithand_data/ffhnet-data
  GAZEBO_OBJ_PATH:  /data/net/userstore/qf/hithand_data/data/gazebo-objects # /home/Dyb/Projects/gazebo-objects
  GRASP_DATA_NANE: grasp_data_all.h5
  POSITIVE_ONLY: True
  NEGATIVE_ONLY: False
  POS_AND_NEG_GRASP: False

GENERAL:
  TOTAL_STEPS: 200000 # 300000 #100000 for train with nll and second 100000 for fintune
  LOG_STEPS: 100
  VAL_STEPS: 100
  # CHECKPOINT_STEPS: 100
  NUM_WORKERS: 8

TRAIN:
  OPT: AdamW # SGD, AdamW
  LR: 1e-4
  WEIGHT_DECAY: 0.0005 # 0.0005
  BATCH_SIZE: 64
  LOSS_REDUCTION: mean
  NUM_TRAIN_SAMPLES: 1
  NUM_TEST_SAMPLES: 1
  BETA1: 0.9

LOSS_WEIGHTS:
  C: -1e4  # truncate value for loss_neg_nll
  ORTHOGONAL: 0.1
  NLL: 1
  KL_NLL: 1
  KL_ENT: 1
  NLL_POS: 1
  NLL_NEG: 1
  ROT: 0.1 # TODO: to be tuned
  TRANSL: 0.1 # In FFHNet, transl coef is 100x of rot coef

MODEL:
  BACKBONE:
    # LATENT_DIM: 5  #FFHGenerator
    PROBABILISTIC: True
    # PRIOR FLOW related
    PRIOR_FLOW: True
    PRIOR_FLOW_GRASP_COND: False
    PRIOR_FLOW_NUM_LAYERS: 4 # numbers of flow layers about [Actnorm, LULinear, Coupling]
    PRIOR_FLOW_LAYER_HIDDEN_FEATURES: 256
    PRIOR_FLOW_LAYER_DEPTH: 2 # number of resblock in resnet
  FLOW:
    BASE: "cond_gaussian" # gmm, gaussian, cond_gaussian, cond_rsb
    # RSB related
    RSB_EPS: 0.01
    RSB_T: 100 
    RSB_ACC_HIDDEN: 128
    RSB_ACC_LAYES: 3
    # GMM related
    GMM_MODE: 1
    GMM_TRAINABLE: True
    # DIM should be 136 for normflow package (split requires even number)
    # DIM is 135 for nflows pacakge.
    DIM: 136 # input dims, also the same dim for base distribution of standard norm
    CONTEXT_FEATURES: 128 # features dim from backbone (TODO: try context_features same dim as DIM)
    NUM_LAYERS: 8 # numbers of layers about [Actnorm, LULinear, Coupling]
    LAYER_HIDDEN_FEATURES: 512 #1024 # hidden layer dims in resnet inside Glow
    LAYER_DEPTH: 4 # number of resblock in resnet

EXTRA:
  FOCAL_LENGTH: 5000
