NAME: test_lvm1
BASE_PACKAGE: normflows # nflows

DATASETS:
  PATH: /data/net/userstore/qf/hithand_data/data/ffhnet-data # /data/hdd1/qf/hithand_data/ffhnet-data
  GAZEBO_OBJ_PATH:  /data/net/userstore/qf/hithand_data/data/gazebo-objects # /home/Dyb/Projects/gazebo-objects
  GRASP_DATA_NANE: grasp_data_all.h5
  POSITIVE_ONLY: True
  NEGATIVE_ONLY: False
  POS_AND_NEG_GRASP: False

GENERAL:
  TOTAL_STEPS: 300000 # 300000 #100000 for train with nll and second 100000 for fintune
  LOG_STEPS: 100
  VAL_STEPS: 100
  # CHECKPOINT_STEPS: 100
  NUM_WORKERS: 8

TRAIN:
  LR: 1e-4
  # WEIGHT_DECAY: 1e-4
  BATCH_SIZE: 64
  LOSS_REDUCTION: mean
  NUM_TRAIN_SAMPLES: 1
  NUM_TEST_SAMPLES: 1
  # from ffhnet
  BETA1: 0.9
  WEIGHT_DECAY: 0.0005

LOSS_WEIGHTS:
  C: -1e4  # truncate value for loss_neg_nll
  ORTHOGONAL: 0.1
  NLL: 1
  KL_NLL: 1
  KL_ENT: 1
  NLL_POS: 1
  NLL_NEG: 1
  ROT: 0.1 # TODO: to be tuned
  TRANSL: 0.1 # In FFHNet, transl coef is 100x of rot coef

MODEL:
  BACKBONE:
    LATENT_DIM: 5  #FFHGenerator
    PROBABILISTIC: True
  FLOW:
    BASE: "gaussian" # gmm, gaussian
    GMM_MODE: 1
    GMM_TRAINABLE: True
    # DIM should be 136 for normflow package (split requires even number)
    # DIM is 135 for nflows pacakge.
    DIM: 136 # input dims, also the same dim for base distribution of standard norm
    NUM_LAYERS: 8 # numbers of layers about [Actnorm, LULinear, Coupling]
    CONTEXT_FEATURES: 128 # features dim from backbone (TODO: try context_features same dim as DIM)
    LAYER_HIDDEN_FEATURES: 512 #1024 # hidden layer dims in resnet inside Glow
    LAYER_DEPTH: 4 # number of resblock in resnet

EXTRA:
  FOCAL_LENGTH: 5000
